### ISSUE TITLE
Accessing public methods for multiple sliders 

### ISSUE THREAD

**Issue by Turgar** [sachinchoolur/lightslider#197]
Hi,

I'm trying to build a page with multiple lightSliders. Each slider works individually, but I can't access any public methods. E.g. this code throws an error if jQuery selects more than one object:

```javascript
var sliders = $('ul.lightslider').lightSlider({ item: 5 });        
sliders[0].refresh(); // Uncaught TypeError: sliders[0].refresh is not a function
```

I really want to do something like this:
```javascript
// event happens, find parent lightslider, call refresh()
$('#content').on('slid.bs.carousel', function (e) { 
    $(e.target).closest('ul.lightslider').refresh();
});
```

Is the second scenario supported? Can I make a different selection or call lightSlider() again?

**Comment by Pilsgaard** [comment]
I'm doing the same thing by making a suffix to each slider and save it in the window variable.

Like 
<div id="light-slider-example1"><ul><li>..</li></ul></div>
window.autoplaySlider_example1 = jQuery("#light-slider-example1").lightSlider();

Regards, 
Casper

**Comment by Turgar** [comment]
Sorry, should've opened this question on SO. I rewrote my local copy of lightSlider.js to support this.

**Comment by xd0** [comment]
@Turgar anything you can share with us?

**Comment by Makkafella** [comment]
Needed exactly this.

This how I did it.
```javascript
var slides = [];
$('.card-image').each(function( index) {
    slides[index] = $(this).find('ul').lightSlider({item: 1});
});

$('body').on('click','.zoom-toggle', function() {
    var itemIndex = $('.zoom-toggle').index(this);
    slides[itemIndex].refresh();
});
```

**Comment by dcorb** [comment]
I needed to have Slider controls outside of the HTML of the lightSlider, and having multiple of them per page. This is how I did it (thanks @Makkafella for the inspiration)

````

           var areaCarousels = [];
          $body.find(".area-carousel").each(function(index){
            areaCarousels[index] = $(this).lightSlider({
              item: 4
            });
          });


         // A bit complex because multiple sliders on 
        //  the page. We need an external array to save
        // lightSlider object (that exposes the API)
          $.each(areaCarousels, function(index){
            var lS_Object = areaCarousels[index];
            var $that = $(lS_Object);
            // .carousel-block is a wrapper outside of .area-carousel
            var $sliderControls = $that.closest('.carousel-block').find('.lSAction.js-custom');
            if ($that.find('.views-row').length > 4) {
              $sliderControls.addClass('enabled')
            }
            $sliderControls.find('.lSNext').on('click',function() {
              lS_Object.goToNextSlide()
            });
            $sliderControls.find('.lSPrev').on('click',function() {
              lS_Object.goToPrevSlide()
            });
          });


````

**Comment by adambichler** [comment]
> I needed to have Slider controls outside of the HTML of the lightSlider, and having multiple of them per page. This is how I did it (thanks @Makkafella for the inspiration)
> 
> ```
> 
>            var areaCarousels = [];
>           $body.find(".area-carousel").each(function(index){
>             areaCarousels[index] = $(this).lightSlider({
>               item: 4
>             });
>           });
> 
> 
>          // A bit complex because multiple sliders on 
>         //  the page. We need an external array to save
>         // lightSlider object (that exposes the API)
>           $.each(areaCarousels, function(index){
>             var lS_Object = areaCarousels[index];
>             var $that = $(lS_Object);
>             // .carousel-block is a wrapper outside of .area-carousel
>             var $sliderControls = $that.closest('.carousel-block').find('.lSAction.js-custom');
>             if ($that.find('.views-row').length > 4) {
>               $sliderControls.addClass('enabled')
>             }
>             $sliderControls.find('.lSNext').on('click',function() {
>               lS_Object.goToNextSlide()
>             });
>             $sliderControls.find('.lSPrev').on('click',function() {
>               lS_Object.goToPrevSlide()
>             });
>           });
> ```

Works like charm! Thanks!
