### ISSUE TITLE
Error with jQuery 3

### ISSUE THREAD

**Issue by pensierinmusica** [sachinchoolur/lightslider#248]
Hi,

Lightslider doesn't seem to work with [jQuery v3.0.0-rc1](https://github.com/jquery/jquery/releases/tag/3.0.0-rc1), as it generates the following error:

```
jquery.js:4 Uncaught TypeError: a.indexOf is not a function
```

I tested it with [jQuery v2.2.4](https://github.com/jquery/jquery/releases/tag/2.2.4) and it works fine. So, it seems to be a breaking change with the new jQuery version.

Can you please check and fix it?

Thanks!

**Comment by davidtgq** [comment]
I'm experiencing the same issue, here is the error trace: [http://i.imgur.com/VWUikTS.png](http://i.imgur.com/VWUikTS.png)

Also, thanks for lighslider and lightgallery, together they saved me a lot of time, and they are much more intuitive to use than slick/photoswipe :)

**Comment by davidtgq** [comment]
I think this may be relevant for that error on line 9608:

> Removed deprecated event aliases
> 
> .load, .unload, and .error, deprecated since jQuery 1.8, are no more. Use .on() to register listeners.
> 
> https://github.com/jquery/jquery/issues/2286

**Comment by cazacugmihai** [comment]
+1

**Comment by hommedeplage** [comment]
Hey guys,
The problem is with `.load()`, it is deprecated in jQuery 3+. From there blog

> .load, .unload, and .error, deprecated since jQuery 1.8, are no more. Use .on() to register listeners.

You can pull this https://github.com/sachinchoolur/lightslider/pull/277/commits/83a94b2e77e345133d84e28ecbcbee43356b6cb9
or just fix it in your version.

**Comment by davidtgq** [comment]
@sachinchoolur Could you please pull this patch https://github.com/sachinchoolur/lightslider/pull/277/commits/83a94b2e77e345133d84e28ecbcbee43356b6cb9 so that we can use it from [cdnjs](https://cdnjs.com/libraries/lightslider)? Thanks

**Comment by sachinchoolur** [comment]
HI Guys,
I've merged the PR.  I'm really sorry for the delay
